version: "3.1"

services:

#  upload-service-app:
#    image: nota-fiscal-upload-service
#    ports: 
#      - "8080:8080"
#    networks:
#      - nota-fiscal-app-network
#    depends_on: 
#      - mysqlserveerdb
      
  mysqlserveerdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2021!"
      MYSQL_DATABASE: "nota-fiscal-db"
    ports:
      - "3306:3306"
    networks:
      - nota-fiscal-app-network
  
networks:
  nota-fiscal-app-network:
    driver: 'bridge'